spring:
  application:
    name: ecs-oms4-einvoice-frontend
  profiles:
    active: sit
  mvc:
    view:
      prefix: /templates
      suffix: .html
  redis:
    host: 47.105.174.28
    password: softone~
    port: 61379
    database: 0

server:
  port: 8080
